spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/career_advisor
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# JWT
jwt.secret=mysecretkeymysecretkeymysecretkey12345

# Flask ML API
ml.api.url=http://127.0.0.1:5000

# Adzuna Jobs API - https://developer.adzuna.com/
adzuna.app.id=a4a5a75e
adzuna.app.key=c9ed7ea3034da6219c1d4d829ca5805b

# YouTube Data API v3 - https://console.cloud.google.com/
youtube.api.key=AIzaSyDVO1WWCJL_AkQwivV3I6KRfUZiEvqbg6E

# Google Custom Search API - same Google Cloud project
# Create search engine at https://programmablesearchengine.google.com/
google.search.api.key=AIzaSyDVO1WWCJL_AkQwivV3I6KRfUZiEvqbg6E
google.search.cx=40b0f1f3219434452
